### ISSUE TITLE
Remove unused cookbook bcpc-centos inherited from bcpc

### ISSUE THREAD

**Issue by kiiranh** [bloomberg/chef-bach#102]
Currently, chef-bach has a cookbook `bcpc-centos` and a few roles which were inherited from the bcpc codebase. We do not use/need them. Such artifacts should be removed from chef-bach code.

**Comment by cbaenziger** [comment]
Also mind pulling [cobbler-centos.rb](https://github.com/bloomberg/chef-bach/blob/725bef69b3ccc13fd592c202b8d4ff009719cc27/cookbooks/bcpc/recipes/cobbler-centos.rb) and [the CentOS image downloads](https://github.com/bloomberg/chef-bach/blob/97d86fa9870d77b3f2cb4ea146178043729982a1/build_bins.sh#L132-L141) with this?

**Comment by bijugs** [comment]
Fixed as part of PR #103.
