### ISSUE TITLE
Remove unused multi-home cruft

### ISSUE THREAD

**Issue by http-418** [bloomberg/chef-bach#1046]
The old bcpc cookbooks are riddled with references to "floating" and "storage" networks that do not exist anywhere internally.

Cluster data and cluster.txt is inaccurate inside a VM cluster because the IP addresses for services change.  Development is more difficult because we are handling special cases that do not exist outside of a toy cluster in VMs.

_None_ of our real environments use this feature.  None have used this feature in my tenure with the firm.  None are likely to use it in the future.

**Comment by cbaenziger** [comment]
This is a very important feature for our testing as we have multi-IP hosts internally. The different NICs simulate having multiple IP options for an interface. This allows us to test fixes such as HBASE-12954 which would otherwise require a physical cluster very different from our test environments.

**Comment by cbaenziger** [comment]
We may be able to get rid of this when we get BGP to the host fully working in VMs and physical hosts, however. At that point they can share the same network design. I suggest we pursue getting the BGP work in, then we can clean-up these older test setups. (For reference, today you can stand a BACH VM cluster with only one interface per VM, if you'd rather.)

**Comment by http-418** [comment]
Our multi-IP setup should look like the configurations in use on physical hardware, not an elaborate ipr2 setup that doesn't get exercised anywhere else.

e.g. there should never be multiple IPs on a worker node.

**Comment by http-418** [comment]
I believe if you configure a single-network VM cluster today, with VIPs, it looks like real clusters do, with multiple IPs bound to the "head" nodes, all on a single interface.  I am verifying that assumption this afternoon.
