### ISSUE TITLE
Chef fails to start hbase-master

### ISSUE THREAD

**Issue by kiiranh** [bloomberg/chef-bach#105]
I came across a rather interesting behavior during my testing of PR #103. Here is what I did and the observation (I did this twice building cluster from scratch.):

1. Run ./test/automated_install.sh with the code @ kiiranh:remove_unused_bcpc_code. This change is for PR #103.
2. After this completes, datanode is not up on VM3.
3. Logon to bootstrap node and run the following *two times*:
`for i in 1 2 3; do ./cluster-assign-roles.sh Test-Laptop Hadoop bcpc-vm$i; done`
4. Check VMs 1 2 and 3. Namenode and datanode services are up. Can perform hdfs operations.
5. However, hbase-master is not started on VM1.
6. Rechef only VM1 again by running `./cluster-assign-roles.sh Test-Laptop Hadoop bcpc-vm1`. hbase-master still doesn't come up. No errors in chef run. base-master logs show no datanode found. But datanode is up and running on VM3.
7. Manually start hbase-master service on VM1. It starts and base operations work! Checked zookeeper and znode /hbase/master *did* exist.
8. Stop hbase-master service on VM1. Rechef all the servers again by running:
`for i in 1 2 3; do ./cluster-assign-roles.sh Test-Laptop Hadoop bcpc-vm$i; done`
9. hbase master is still not up on VM1. This time logs show failure to come up due to Zookeeper. Exception: 
` WARN org.apache.hadoop.hbase.zookeeper.ZooKeeperNodeTracker: Can't get or delete the master znode
org.apache.zookeeper.KeeperException$SessionExpiredException: KeeperErrorCode = Session expired for /hbase/master`
Checked zookeeper and znode /hbase/master *did not* exist.
10. Rechef just VM1 again by running: `./cluster-assign-roles.sh Test-Laptop Hadoop bcpc-vm1`. hbase-master failed to come up with same zookeeper exception.
11. Manually start hbase-master on VM1 and it starts and works.

Net: Chef cannot seem to start hbase-master service on VM1. Manually starting it works. Multiple chef runs do not help.

**Comment by kiiranh** [comment]
@bijugs pointed out the root cause for this bug. 
[hbase-master resource|https://github.com/bloomberg/chef-bach/blob/master/cookbooks/bcpc-hadoop/recipes/hbase_master.rb#L46-L51] in the recipe does not specify supports attribute which means chef uses ps and grep to seed if a process with substring base-master is running. With the recent flume/copy-logs change, a flume process is started with tracks the hbase-master log and hence chef fails to start hbase-master service.
Fix is to add supports attribute to the service resource linked above.

**Comment by cbaenziger** [comment]
Ah marking as a dup of #53 this affects more than HBase if I recall correctly. We should fix all of our services.
