### ISSUE TITLE
cluster address is blank in vm1 when mysql recipe is run

### ISSUE THREAD

**Issue by vineshcpaul** [bloomberg/chef-bach#1091]
MySQL fails to start as the cluster address is blank in /etc/mysql/conf.d/wsrep.cnf

[0m    Mixlib::ShellOut::ShellCommandFailed^[[0m^M^M
    ------------------------------------^[[0m^M^M
    Expected process to exit with [0], but received '1'^M^M
^[[0m    ---- Begin output of /etc/init.d/mysql start ----^M^M
^[[0m    STDOUT: * Starting MySQL (Percona XtraDB Cluster) database server mysqld^M^M
^[[0m     * The server quit without updating PID file (/var/run/mysqld/mysqld.pid).^M^M
^[[0m       ...fail!^M^M
^[[0m    STDERR: ^M^M
^[[0m    ---- End output of /etc/init.d/mysql start ----^M^M
^[[0m    Ran /etc/init.d/mysql start returned 1^[[0m^M^M
    ^M^M
^[[0m    Resource Declaration:^[[0m^M^M

**Comment by aespinosa** [comment]
the `wsrep.conf` files are meant to only include "other heads" in the cluster
