### ISSUE TITLE
codify HBase namespace tenancy policies

### ISSUE THREAD

**Issue by aespinosa** [bloomberg/chef-bach#1106]
For setting up tenancies like ACLs, (and quotas in the future)

Some permissions:

(Updated)
* `RCWAX` for the actual namespace
* `RX` to `SYSTEM:CATALOG` for Phoenix
* `RX` to `hbase:meta`

**Comment by saumilmayani** [comment]
Hi @aespinosa 
set RX for SYSTEM:CATALOG and hbase:meta.

**Comment by aespinosa** [comment]
Thanks @saumilmayani !
