### ISSUE TITLE
document: make_config doesn't update existing item

### ISSUE THREAD

**Issue by leochen4891** [bloomberg/chef-bach#1129]
I don't expect the behavior of the [make_config ](https://github.com/leochen4891/chef-bach/blob/7529269511df730c82aab99f8ad4c660679b8db2/cookbooks/bcpc/libraries/utils.rb#L91)function in `cookbooks/bcpc/libraries/utils.rb`.
I'm trying to save the newly generated ssh public key ([code](https://github.com/leochen4891/chef-bach/blob/7529269511df730c82aab99f8ad4c660679b8db2/cookbooks/bcpc/recipes/certs.rb#L46)), however it is not updated, but the existing value is returned.
```
Recipe: bcpc::certs
  * ruby_block[generate-ssh-keypair] action run============ Loaded existing item with key "ssh-public-key"
```
If the function behavior is correct, it may need some comments.

**Comment by cbaenziger** [comment]
Hi @leochen4891, you are hitting the [lines](https://github.com/bloomberg/chef-bach/blob/6146ad09d1a59cfb264924e940bd841a5992ffd7/cookbooks/bcpc/libraries/utils.rb#L99-L103) in `make_config` which indeed returns the already set value -- often in the code we use `make_config` without a guard to `get_config`.

If `make_config` creates a new value it prints out an `INFO` log message `++++++++++++ Creating new item with key "#{key}"`. Meanwhile, if it is simply returning a value, it prints out `============ Loaded existing item with key "#{key}"`.

This function ought to indeed have a nice comment atop like [`get_config`](https://github.com/bloomberg/chef-bach/blob/6146ad09d1a59cfb264924e940bd841a5992ffd7/cookbooks/bcpc/libraries/utils.rb#L105-L108) just below to document this.

**Comment by leochen4891** [comment]
Without an update_config function, it would be a little bit awkward to use get_config, make_config, and delete_config to perform an update operation. Do you think it would help to add an update_config function in this case?

**Comment by cbaenziger** [comment]
Indeed, we have never had the use-case to update a configuration before. The thought in the past is we do not want to mutate state too much on the Chef-Server so we can download it and upload it to external stores (like a password vault) or to back it up for Chef-Server HA.

Why do you want to change the SSH key change? (This defeats the purpose of an SSH [known-host file](https://www.ssh.com/ssh/host-key#sec-Known-Host-Keys) or SSH finger-print DNS records.)
