### ISSUE TITLE
Add support for node numbers > 8 bits in cluster.txt

### ISSUE THREAD

**Issue by amithkanand** [bloomberg/chef-bach#1144]
With latest change to get cluster information statically, it doesn't allow node numbers greater than 8 bits. We need to add support to `cluster.tx`t to allow node numbers that are greater than 8 bit.

**Comment by pu239ppy** [comment]
Why do you need node numbers greater then 8 bits?  as of #1009 Worker nodes no longer receive a node ID, which mean your entire 8 bit ranger (does 0 constitute a valid ID) may be used for head nodes only.  So unless you plan to have more then 8 bits of Head nodes, this is unnecessary.  Furthermore I was under the impression that 8bit IDs was a hard requirement from zookeeper.

**Comment by aespinosa** [comment]
Do you mind expanding the impact of changing node numbers at namenodes and resource managers during the migration?

1.  namenode A (standby) has node_number > 8 bit
2.  chef namenode A.  node_number of A will become < 8 bit . namenode A points to namenode B via namenode B's new < 8bit node_number.  Can namenode A still connect to namenode B and vice versa?

Richard's currently working on testing the upgrade path so we'll know what to expect in the upgrade path.

**Comment by http-418** [comment]
We have to preserve existing node numbers, because otherwise we will experience downtime during the upgrade.

Existing node numbers are often greater than 8 bits, and then they are modulo'd down to the 8 bit range for use by zookeeper.

All future nodes/clusters will have simple node numbers < 255, for simplicity.  But our existing clusters have to retain their current numbers.

**Comment by pu239ppy** [comment]
@http-418 if you have an existing node number > 8bit it will be converted to number mod 8 for zookeeper anyway, why not take that number and use it as a new node number.  The only caveat here is that you will have to suffer restarts for HDFS and YARN that use the full number as opposed to number mod 8.  However the benefit is that you will never accidentally conflict with another nodes node number while picking a new number, and you do not have to check this manually by picking a number and running mod 8 on existing numbers.

**Comment by bijugs** [comment]
``node number > 8bit it will be converted to number mod 8 for `` -> is there a possibility of creating duplicate node id or we are handling that as well?

**Comment by pu239ppy** [comment]
@bijugs C-A-R will warn you that your `node_number mod 8` conflicts with other `node_number mod 8`, however as I said above if you accept the tradeoff of having to re-converge your entire node at least as far as HDFS NN/JN/DN and YARN RM/NM daemons go, then you will not have to deal with this issue

**Comment by http-418** [comment]
As another wrinkle here, it doesn't look like node[:bcpc][:node_number] is derived from cluster ID saved in cluster.txt.  It has to be manually copied into place, and the node saved.

We should do this automatically.   Here is a workaround for the time being.  After C-A-R "stubs," but before C-A-R basic, load chef-shell and run this handy one-liner.
```
sudo chef-shell -z -o 'bach_hadoop_wrapper'

require 'cluster_def'; BACH::ClusterDef.new.fetch_cluster_def().map { |ss| nn = Chef::Node.load(ss[:fqdn]); nn.normal[:bcpc][:node_number] = ss[:node_id]; nn.save }
```
