### ISSUE TITLE
add timeout to resource locking

### ISSUE THREAD

**Issue by leochen4891** [bloomberg/chef-bach#1166]
If a node is holding a lock for a prolonged period of time (e.g. go offline for hardware maintenance), it prevents other nodes from getting the lock and therefore cannot chef.
A timeout should be applied when a lock is being hold.

**Comment by aespinosa** [comment]
@cbaenziger mentioned that the infinite lock was a design decision to prevent bad config from propagating further.

**Comment by aespinosa** [comment]
as commented earlier, it's a feature. not a bug :)
