### ISSUE TITLE
failure while building hdfsdu sources

### ISSUE THREAD

**Issue by vineshcpaul** [bloomberg/chef-bach#1172]
The following failure is seen on master when the hdfsdu cookbook tries to build  sources from 
https://github.com/twitter/hdfs-du.

^[[0m    [FATAL] Non-resolvable parent POM for com.twitter.hdfsdu:hdfsdu:0.1.0: Could not transfer artifact org.sonatype.oss:oss-parent:pom:7 from/to twitter (http://maven.twttr.com): java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty and 'parent.relativePath' points at wrong local POM @ com.twitter.hdfsdu:hdfsdu:0.1.0, /var/chef/cache/hdfsdu/pom.xml, line 6, column 11^M

This looks like is an issue when it is trying to resolve dependencies from a repository that is hosted at https://maven.twttr.com/com/twitter/common/..

It might be that the site is unreliable and does not download the dependent artifacts .
Moreover, this site seems to be outdated and not maintained as per this [link](https://finagle.github.io/blog/2016/11/29/central-libthrift/) and some of the artifacts are being moved to central repository.

The following issue is opened on the hdfsdu github for this error.
https://github.com/twitter/hdfs-du/issues/14

**Comment by cbaenziger** [comment]
Hi @vineshcpaul I think we are good to close this now, right? Please re-open this if it is still broken for you.
