### ISSUE TITLE
Maven issues

### ISSUE THREAD

**Issue by bijugs** [bloomberg/chef-bach#1175]
Came across the following two issues with ``Maven``

- Attributes related to ``Maven`` opts were set only if there are custom certs which is [changed](https://github.com/http-418/chef-bach/blob/2993fc8a1191aae795732bad03139ecb12530a72/cookbooks/bcpc-hadoop/recipes/maven_config.rb#L36) as part of a recent commit. This results in cluster build failures.
- ``/usr/local/maven/conf/settings.xml`` is not getting updated when a custom ``Maven`` repo ``URL`` is provided resulting in using the default ``Maven`` repo.

**Comment by http-418** [comment]
I believe this is resolved.

**Comment by cbaenziger** [comment]
I think we may have one more issue here. On an Internet connected hosts the following code runs but there is no MITM to worry about:
https://github.com/bloomberg/chef-bach/blob/805bc2cc407e720fad0d329c1b87ef0a5114e515/cookbooks/bcpc-hadoop/recipes/maven_config.rb#L33-L39
