### ISSUE TITLE
Building master fails due to Vagrant box changes

### ISSUE THREAD

**Issue by cbaenziger** [bloomberg/chef-bach#1176]
I am seeing issues building master; many: `undefined method '[]' for nil:NilClass` errors due to missing Ohai dmi variables, e.g. from [bach-variables.erb](https://github.com/bloomberg/chef-bach/blob/219afb54a070a938a43bcd2e1e517ec2439282ca/cookbooks/bach_common/templates/default/motd/bach-variables.erb#L10-L11):
```
mfg = node['dmi']['system']['manufacturer']
product = node['dmi']['system']['product_name']
```

It seems this is due to some change in the Vagrant box upstream as Ohai only provides the following:
```
"dmi": {
    "dmidecode_version": "2.12"
},
```

And running `dmidecode` on the command-line provides:
```
ubuntu@bcpc-vm1:~$ sudo dmidecode 
# dmidecode 2.12
/sys/firmware/efi/systab: SMBIOS entry point missing
```

**Comment by cbaenziger** [comment]
If commenting out the MOTD bits, one then runs into VBox checks in:
* [cookbooks/bcpc/libraries/disk_helper.rb:92:in `bcpc_unused_disks](https://github.com/bloomberg/chef-bach/blob/b9ad223ae7e01fde21b05b5889a6d8f5d014ec03/cookbooks/bcpc/libraries/disk_helper.rb#L92)

**Comment by http-418** [comment]
I cannot recreate this.  I'm on Virtualbox 5.0.40, and dmidecode stuff works for me.

**Comment by cbaenziger** [comment]
Which version is your Vagrant box? I suspect it's not a VirtualBox change.

**Comment by cbaenziger** [comment]
For reference I see I have:
```cwb@precise:~/work/oozie_retest_rebase_4_18_18$ vagrant box list
bento/centos-6.7   (virtualbox, 2.2.7)
bento/centos-7.2   (virtualbox, 2.3.1)
bento/ubuntu-12.04 (virtualbox, 2.3.1)
bento/ubuntu-14.04 (virtualbox, 2.3.1)
bento/ubuntu-16.04 (virtualbox, 2.3.1)
trusty64           (virtualbox, 0)
```

**Comment by cbaenziger** [comment]
@ronny-macmaster has found newer boxes also seem to have `127.0.1.1` as localhost instead of `127.0.0.1` as well.
