### ISSUE TITLE
Remove code downloading unused software

### ISSUE THREAD

**Issue by bijugs** [bloomberg/chef-bach#120]
Can we remove downloading unused software like elasticsearch which is not currently used in our stack. There may be others as well which we can include to this list.

https://github.com/bloomberg/chef-bach/blob/master/build_bins.sh#L89
https://github.com/bloomberg/chef-bach/blob/master/build_bins.sh#L157
https://github.com/bloomberg/chef-bach/blob/master/build_bins.sh#L162

**Comment by cbaenziger** [comment]
If we pull Elastic Search, I would like to pull the associated bits too:
* [elasticsearch.rb](https://github.com/bloomberg/chef-bach/blob/df00e69072162b6eed89544ac9c91a12d0407e9a/cookbooks/bcpc/recipes/elasticsearch.rb)
* [fluentd.rb](https://github.com/bloomberg/chef-bach/blob/df00e69072162b6eed89544ac9c91a12d0407e9a/cookbooks/bcpc/recipes/recipes/fluentd.rb)
* [haproxy.rb elasticsearch mentions](https://github.com/bloomberg/chef-bach/blob/master/cookbooks/bcpc/recipes/haproxy.rb#L49)

**Comment by bijugs** [comment]
We will also need to remove ``kibana`` components along with ``elasticsearch``.

**Comment by bijugs** [comment]
Fixed as part of PR #126 . Thanks @cbaenziger .
