### ISSUE TITLE
wait-for-hosts loops forever until the user manually connects to serial consoles

### ISSUE THREAD

**Issue by ronny-macmaster** [bloomberg/chef-bach#1228]
Sal and Ron have found that connecting to each serial console in turn will fix the shell script checks for living VMs.

We should probably drop serial console support entirely.  We can't troubleshoot boot problems on VMs or physical hardware via serial console, so the first step in every troubleshooting process is to open a video console.

**Comment by vt0r** [comment]
Fixed in #1242
