### ISSUE TITLE
Master broken looking for missing recipe bcpc-hadoop::hdfs_web

### ISSUE THREAD

**Issue by cbaenziger** [bloomberg/chef-bach#1286]
Building on master recently broke looking for `bcpc-hadoop::hdfs_web` it looks like [`namenode_master.rb`](https://github.com/bloomberg/chef-bach/blob/5a63427e96f8870732b1a4875e9a5e4236d66b46/cookbooks/bcpc-hadoop/recipes/namenode_master.rb#L6) still includes this but `hdfs_web.rb` was removed in [#1282](https://github.com/bloomberg/chef-bach/pull/1282/files#diff-e77ee88b9c54b40662c900caee407052).

**Comment by ronny-macmaster** [comment]
We also need to remove references to bcpc-hadoop::hbase_web. A simple grep of the cookbooks dir for bcpc-hadoop::hbase_web and bcpc-hadoop::hdfs_web should reveal all of the dangling references. I could build a vm cluster after removing all of these include_recipe calls.

**Comment by ronny-macmaster** [comment]
Fixed in #1287
