### ISSUE TITLE
Automated install script should have a time bound on check to see if servers are up

### ISSUE THREAD

**Issue by kiiranh** [bloomberg/chef-bach#129]
[AutoInstall](https://github.com/bloomberg/chef-bach/blob/master/tests/automated_install.sh#L58-L69) currently runs an endless loop to check if the VMs are up. This is not helpful if indeed there is a problem with the VM bringup. The loop should be bound to run x number of times where x = <Expected time for VM to be up>/60 (since we sleep for 60s between iterations of loops).

**Comment by bijugs** [comment]
@kiiranh . I am not sure whether we can define a max boundary since this will vary with the hypervisor on which the cluster is being built!! May be users are the best judge on this. One usability suggestion will be to have an upper bound after which we remind the users using console message to check the state of the node machines.

**Comment by kiiranh** [comment]
I was thinking of fail-fast. For auto-install we typically, install 3/4 VMs for the cluster and  setting even 15-20min would be better than letting it run for hours.

**Comment by bijugs** [comment]
@kiiranh . I have seen VM creations take more time than 15 - 20 mins when running on my Laptop. More over if you set a 15 - 20 min limit there is a possibility that you may end the run when the VMs are about to be ready which will force the user start over again. Better we give the warning with commands and let the user take the action after checking the state of the VMs.

**Comment by cbaenziger** [comment]
All traffic for the VM's has to go through the bootstrap, I think there's a pretty deterministic way to determine the installer is pulling bits or not. Certainly, on some of our machines VM creation takes > 40 minutes and is successful.

**Comment by kiiranh** [comment]
In that case, a console message to user won't be of much either. We better leave it as is. Onus is on the user to check the nodes manually.
