### ISSUE TITLE
Automatic iPXE booting from Cobbler

### ISSUE THREAD

**Issue by vt0r** [bloomberg/chef-bach#1298]
Issues fixed in #1297 :
- [x] The root disk selection script now works
  - [x] Now it also supports NVMe volumes

Remaining issues to resolve:
- [ ] iPXE loops forever, handing out the EFI boot image when the iPXE boot script should be passed. DHCP replies look fine.
- [ ] We need a method to append kernel parameters to only certain hosts that doesn't require modifying the `add_kernel_opts` for the entire cluster.
  - [ ] This can probably be accomplished using `cobbler system edit` and `kopts`

**Comment by cbaenziger** [comment]
I thought the `add_kernel_opts` was supported by the cobbler profile option in `cluster.txt`?

**Comment by aespinosa** [comment]
that's only for netboot parameters. what goes into the actual kernel post installation is defined in the preseed.
