### ISSUE TITLE
Service ports have changed in HDP 2.2

### ISSUE THREAD

**Issue by kiiranh** [bloomberg/chef-bach#130]
While testing hannibal on HDP 2.2, I noticed that hbase region server ports (60020, 60030) have changed to (60200, 60300) respectively. This breaks hannibal. Need to evaluate the changes in all the core component ports and how to handle them.

**Comment by kiiranh** [comment]
Hortonworks hasn't changed the ports in 2.2 according to their [documentation]()
https://github.com/cbaenziger/chef-bach/blob/master/cookbooks/bcpc-hadoop/templates/default/hdp_hbase-regionserver-initd.erb#L83-L92

**Comment by kiiranh** [comment]
Fix merged. Closing this issue.

**Comment by cbaenziger** [comment]
@kiiranh Again, HBase ports changed in HDP2.3 as part of [HBASE-10123](https://issues.apache.org/jira/browse/HBASE-10123).
