### ISSUE TITLE
configure_kerberos usage and using 

### ISSUE THREAD

**Issue by cbaenziger** [bloomberg/chef-bach#1301]
# Need to use `configure_kerberos` in wrapper recipes:
For example, the code in [smoke_test_wrapper](https://github.com/bloomberg/chef-bach/blob/0f2f37662359579e0f6023cc7cc02e8ac43aabfe/cookbooks/bcpc-hadoop/recipes/smoke_test_wrapper.rb#L80-L92) could much better use [configure_kerberos](https://github.com/bloomberg/chef-bach/blob/3f768e717853507bc71b7b724b3fe6a8f726cdb1/cookbooks/bcpc-hadoop/definitions/configure_kerberos.rb).

**Comment by aespinosa** [comment]
IIRC `configure_kerberos` can't handle non-host keytabs or something. Needs to be refactored to be able to  generate "user keytabs"

**Comment by ronny-macmaster** [comment]
here's a useful extended grep for finding all of the references to the keytab dir attribute in the cookbooks:  `egrep -irn "\[[:'\"]?keytab['\"]?\]\[[:'\"]?dir['\"]?\]" cookbooks/`

**Comment by cbaenziger** [comment]
It seems what got my attention with smoke_test_wrapper is that I was accidentally running with kerberos disabled for reference. Thanks for the [heads-up](https://github.com/bloomberg/chef-bach/issues/1301#issuecomment-435447338) @aespinosa.
