### ISSUE TITLE
Java still inconsistent

### ISSUE THREAD

**Issue by cbaenziger** [bloomberg/chef-bach#136]
In the [process](https://github.com/bloomberg/chef-bach/commit/42769e37d031d777d3e564d87451f87c5a3d8dff) to make Java configurable, some components were missed:
* HBase has a hardcoded [Java home](https://github.com/bloomberg/chef-bach/blob/f77aa3c522592b63a9464bc1eb5cee9e47275ded/cookbooks/bcpc-hadoop/templates/default/hb_hbase-env.sh.erb#L108)
* HTTPFS does not have a [subscribe](https://github.com/bloomberg/chef-bach/blob/fae16780f88045c61a74ce555d539167465b31b2/cookbooks/bcpc-hadoop/recipes/httpfs.rb#L11) on `hadoop-env.sh`
* Zookeeper uses an arbitrary Java. From `/usr/lib/zookeeper/bin/zkEnv.sh`, it seems Java can be set via `$JAVA_HOME` in:
  * `${ZOOCFGDIR}/zookeeper-env.sh`
  * `$ZOOCFGDIR/java.env`

**Comment by kiiranh** [comment]
Additionally, the following processes don't restart when Java is updated:
* Namenode
* Journalnode
* Flume
* Hive

**Comment by cbaenziger** [comment]
I believe [Chef-BACH #136](https://github.com/bloomberg/chef-bach/commit/72cffa539ee88bc4c353f66db505491fd5da711f#diff-77621e1ef47ca04a004ebd1da1a5fbf8R9) fixed this.
