### ISSUE TITLE
Need to stand up YARN Application Timeline Server

### ISSUE THREAD

**Issue by cbaenziger** [bloomberg/chef-bach#146]
We should be deploying the [YARN Application Timeline Server](http://hadoop.apache.org/docs/current/hadoop-yarn/hadoop-yarn-site/TimelineServer.html). Further investigation should go into [TEZ-8](https://issues.apache.org/jira/browse/TEZ-8). Lastly, as noted in #64, should YARN Proxy be properly deployed?

**Comment by arunvoma** [comment]
This is fixed in PR #150

**Comment by arunvoma** [comment]
I have submitted the initial version of code  and it's in-progress.

**Comment by pu239ppy** [comment]
fixed in #717
