### ISSUE TITLE
Missing closing XML tag

### ISSUE THREAD

**Issue by amithkanand** [bloomberg/chef-bach#148]
Configuration file template [`cookbooks/bcpc-hadoop/templates/default/hdp_ssl-server.xml.erb`](https://github.com/bloomberg/chef-bach/blob/master/cookbooks/bcpc-hadoop/templates/default/hdp_ssl-server.xml.erb#L36-L37) is missing closing `</description>` tag.

**Comment by cbaenziger** [comment]
Fixed in #117
