### ISSUE TITLE
Fix Hive Aux Jar parth

### ISSUE THREAD

**Issue by amithkanand** [bloomberg/chef-bach#152]
HDP2.2 [``hv_hive-env.sh.erb``](https://github.com/bloomberg/chef-bach/blob/master/cookbooks/bcpc-hadoop/templates/default/hv_hive-env.sh.erb#L7) points to incorrect location for ``hcatalog-core.jar`` causing hive to not work correctly. The path should be fixed to correct location as installed by HDP2.2.

**Comment by cbaenziger** [comment]
Committed in #143
