### ISSUE TITLE
Broken HTTFPS in HDP2.2

### ISSUE THREAD

**Issue by amithkanand** [bloomberg/chef-bach#153]
HTTPFS component doesn't work in HDP2.2. Following issues have been found during setting up and testing it. 
- Service script sources [incorrect](https://github.com/bloomberg/chef-bach/blob/master/cookbooks/bcpc-hadoop/templates/default/hdp_hadoop-httpfs-initd.erb#L35) files that are not deployed anymore by HDP2.2 installation
- HTTPFS Environment file is missing many export parameters
- HTTPFS installation is missing link to ``server.xml`` to start ``CATALINA``

**Comment by cbaenziger** [comment]
Committed in #143
