### ISSUE TITLE
Remove HIVE parameters from hadoop-env.sh

### ISSUE THREAD

**Issue by amithkanand** [bloomberg/chef-bach#155]
Currently [``hadoop-env.sh``](https://github.com/bloomberg/chef-bach/blob/master/cookbooks/bcpc-hadoop/templates/default/hdp_hadoop-env.sh.erb#L12-L17) defines `HIVE` related parameters that are also defined in [``hive-env.sh``](https://github.com/bloomberg/chef-bach/blob/master/cookbooks/bcpc-hadoop/templates/default/hv_hive-env.sh.erb#L3-L7). These parameters do not need to be present in `hadoop-env.sh` and should be removed.

**Comment by cbaenziger** [comment]
Committed in #143
