### ISSUE TITLE
Run chef-client daemon with custom client.rb

### ISSUE THREAD

**Issue by kiiranh** [bloomberg/chef-bach#169]
One can have a node chef'd periodically by starting a chef-client process on the node (include `recipe[chef-client::init_service]` in node's runlist). All this works fine when the node's client key is present in `/etc/chef/` directory; for e.g.; `/etc/chef/client.pem`. But if the node's key is not present in that location and you use a [custom client.rb script](https://github.com/bloomberg/chef-bach/blob/master/setup_chef_cookbooks.sh#L25-L56) as with [chef-bach's bootstrap node](https://github.com/bloomberg/chef-bach/blob/master/setup_chef_bootstrap_node.sh#L32), chef-client fails because it cannot find node's key in /etc/chef/ directory.
This only affects the bootstrap node. There should be a way to have chef-client use the [bootstrap nodes' key](https://github.com/bloomberg/chef-bach/blob/master/setup_chef_cookbooks.sh#L35) at a different location than /etc/chef/...

**Comment by cbaenziger** [comment]
Merged
