### ISSUE TITLE
Oozie sharelib directory changed between hdp2.0 to hdp2.2 and is cryptic

### ISSUE THREAD

**Issue by kiiranh** [bloomberg/chef-bach#178]
On hdp2.0, the oozie sharelib directory on hdfs was /user/oozie/share/lib. In the hdp2.2 installation, that changed to /user/oozie/share/lib/lib_<some number> (eg: /user/oozie/share/lib/lib_20150605140532). This change of path could possibly break existing users after upgrading to hdp2.2.

**Comment by kiiranh** [comment]
After some analysis, found that the [code that initiates oozie sharelib setup](https://github.com/bloomberg/chef-bach/blob/master/cookbooks/bcpc-hadoop/recipes/oozie.rb#L104-L116) was change under commits [073ab64](https://github.com/bloomberg/chef-bach/commit/073ab64d1655abcd34fa9bfd980d78b38e7afe60). It now calls `oozie-setup.sh sharelib upgrade` which internally calls [OozieSharelibCLI.java](https://github.com/apache/oozie/blob/master/tools/src/main/java/org/apache/oozie/tools/OozieSharelibCLI.java). And for whatever reason, that class [creates a new directory lib_<current timestamp>](https://github.com/apache/oozie/blob/master/tools/src/main/java/org/apache/oozie/tools/OozieSharelibCLI.java#L151-L153) in `hdfs:///user/oozie/share/lib` instead of just copying over the libs in  `hdfs:///user/oozie/share/lib`.

**Comment by kiiranh** [comment]
So the changes may not have been caused by hdp2.0->hdp2.2, but the chef-bach code change which was changed to use the [upgrade](https://github.com/bloomberg/chef-bach/blob/master/cookbooks/bcpc-hadoop/recipes/oozie.rb#L107) option. The libraries in the lib_<timestamp> directory could still work, but it would be good to have consistency in oozie sharelib paths.

**Comment by kiiranh** [comment]
Also, the [temp file](https://github.com/bloomberg/chef-bach/blob/master/cookbooks/bcpc-hadoop/recipes/oozie.rb#L110) created during share lib setup on hdfs isn't cleaned up correctly. This could skip sharelib upgrade in the next chef-client run.

**Comment by cbaenziger** [comment]
For some more background on Oozie shared-libs:
* [Step 4 of the Hortonworks 2.1 to 2.2 upgrade guide](http://docs.hortonworks.com/HDPDocuments/HDP2/HDP-2.2.6/bk_upgrading_hdp_manually/content/start-oozie-21.html)
* [Oozie Initial Shared-Lib Rationale](http://blog.cloudera.com/blog/2012/12/how-to-use-the-sharelib-in-apache-oozie/)
* [Oozie Upgradeable Shared-Lib](http://blog.cloudera.com/blog/2014/05/how-to-use-the-sharelib-in-apache-oozie-cdh-5/)

Clearly this recipe needs some clean-up!

**Comment by kiiranh** [comment]
In Upgrade, after running the sharelib creation again, Oozie will automatically pick up the sharelib dir with the latest timestamp as the new sharelib dir. 

One can confirm by checking the oozie.log. (/var/log/oozie/oozie.log) 

Snippet from a sandbox. 
*************** 
2015-07-06 21:10:37,269 INFO ShareLibService:543 - SERVER[sandbox.com] USER[-] GROUP[-] Share lib for oozie:[hdfs://sandbox.com:8020/user/oozie/share/lib/lib_20141216191026/oozie/json-simple-1.1.jar, hdfs://sandbox.com:8020/user/oozie/share/lib/lib_20141216191026/oozie/oozie-hadoop-utils-2.6.0.2.2.0.0-2041.oozie-4.1.0.2.2.0.0-2041.jar, hdfs://sandbox.com:8020/user/oozie/share/lib/lib_20141216191026/oozie/oozie-sharelib-oozie-4.1.0.2.2.0.0-2041.jar] 
***************

**Comment by kiiranh** [comment]
*Another issue* Oozie server should be restarted after sharelib is updated.

After an upgrade (specially since I think you are not using Ambari), run the pig smoke test manually, and if there is a failure, pls make sure: hadoop-lzo jar etc. from /usr/lib/hadoop/lib are copied to /usr/lib/oozie/libext/ and the oozie server is restarted.

**Comment by kiiranh** [comment]
The related  PR is merged. Closing this issue.
