### ISSUE TITLE
Incorrect configuration location in mapred-site.xml

### ISSUE THREAD

**Issue by amithkanand** [bloomberg/chef-bach#185]
In `mapred-site.xml` the parameter `mapreduce.application.classpath` defines `/etc/hadoop/conf/secure` as location for `hadoop` configuration files. This causes incorrect location to be picked up within `mapper` of a `MR` job. 
For example:

```
FileSystem.get(new Configuration()) Within mapper of a MR Job defaults to local 
filesystem and this causes the following code to fail 
fs = FileSystem.get(new Configuration()) 
fs.exists(hdfs://user/xxx/a.txt)
```

The fix is to remove `/etc/hadoop/conf/secure` from the classpath.

**Comment by cbaenziger** [comment]
Hrm, it is strange an empty directory in the CLASSPATH would break things so badly? Does any empty directory do this?
