### ISSUE TITLE
Set ULIMIT to a higher value for root user

### ISSUE THREAD

**Issue by amithkanand** [bloomberg/chef-bach#205]
In case of secure `datanode`, the process is first started as `root` followed by a child process (actual datanode process). The start of secure `datanode` is handled by `JSVC` program that doesn't pass actual `ULIMIT` value to the child process while launching it. 
We should set `ULIMIT` to `32K` for the `root` user.

**Comment by cbaenziger** [comment]
I would prefer to modify the datanode startup script to run `ulimit -n 32768` before calling the Bigtop JSVC program which launches the daemon.

**Comment by amithkanand** [comment]
Closing as PR #243 is merged.
