### ISSUE TITLE
MOTD

### ISSUE THREAD

**Issue by cbaenziger** [bloomberg/chef-bach#237]
Today, our cluster VM's have the default Ubuntu message-of-the-day. This is not user friendly. We should instead provide a message which gives some key details (and perhaps an environmentally configurable string).

Important info:
* Cluster Name (Chef environment name)
* Machine role or run list (ideally in a prettified form)
* Perhaps other machines in the cluster? (Or perhaps headnodes?)

**Comment by pu239ppy** [comment]
Looks good

**Comment by http-418** [comment]
PR 238 was merged some time ago.
