### ISSUE TITLE
HAPROXY Chef Vaulting breaks auto chef-ing of nodes

### ISSUE THREAD

**Issue by amithkanand** [bloomberg/chef-bach#244]
After `HAPROXY` password was chef-vaulted, auto chef-ing of cluster head nodes breaks as head nodes are made admin during process of `cluster-assign-roles.sh`. In case of existing clusters we do not run `cluster-assign-roles.sh` and nodes are expected to auto chef. As per current logic the first head node will be able to successfully create the `HAPROXY STATS` password vault but since `cluster-assign-roles.sh` is not run, other head nodes won't be admin on the vault. 
In case of existing clusters head nodes should be able to become admin on the chef vault created by first head node.

**Comment by cbaenziger** [comment]
Hi Ray,

I would recommend that if the password being created already exists, you add all machines which are currently set to run the current recipe to the admins list at [haproxy.rb:35](https://github.com/bloomberg/chef-bach/blob/771eebaae91fdf58c89b566db13c9ad9b467b632/cookbooks/bcpc/recipes/haproxy.rb#L35). Also, can you investigate why the Chef vault data bag isn't created if not created by `cluster-assign-roles.sh`?

**Comment by DrRayWang** [comment]
Chef vault data bag item is not created in C-A-R.sh, it is created when the recipe, like haproxy.rb, gets run at the first time. New change has been made to fix this issue in PR#245.

**Comment by cbaenziger** [comment]
Closing as clusters which pre-date chef-vaulting are becoming rare and this has been largely addressed.
