### ISSUE TITLE
Kerberos Breaks Build

### ISSUE THREAD

**Issue by cbaenziger** [bloomberg/chef-bach#258]
After Chef-BACH #117 went in my build now breaks with:
````
================================================================================
Recipe Compile Error in /var/chef/cache/cookbooks/bcpc-hadoop/recipes/configs.rb
================================================================================


NoMethodError
-------------
undefined method `[]' for nil:NilClass


Cookbook Trace:
---------------
  /var/chef/cache/cookbooks/bcpc-hadoop/recipes/configs.rb:76:in `from_file'


Relevant File Content:
----------------------
/var/chef/cache/cookbooks/bcpc-hadoop/recipes/configs.rb:

 69:  %w{zookeeper}.each do |pkg|
 70:    package pkg do
 71:      action :upgrade
 72:    end
 73:  end
 74:  
 75:  # Create Keytabs (if kerberos is eanbled)
 76>> if node[:bcpc][:hadoop][:kerberos][:enable] == true then
````

I suspect a missing default `node[:bcpc][:hadoop][:kerberos][:enable]=false` is needed?

**Comment by cbaenziger** [comment]
A key part to triggering this is having an environment file from before #117 merged.

**Comment by kiiranh** [comment]
The only default setting for this attribute is in the environment file. So, ofcourse it will break with the environment file from before #117 . A fix and good practice would be to have a `nil?` check for the attribute OR we could have a default attribute in `bcpc-hadoop` as suggested above.

**Comment by pu239ppy** [comment]
I did not see it in the environment, if this is where it should be I can resubmit the PR

**Comment by kiiranh** [comment]
A `default` attribute in `bcpc-hadoop` should be fine.

**Comment by pu239ppy** [comment]
Spoke too soon, this is indeed in the environment, issue may be closed
