### ISSUE TITLE
Correct graphite log cleanup

### ISSUE THREAD

**Issue by kiiranh** [bloomberg/chef-bach#272]
[Commit eaa9bb0a0](https://github.com/bloomberg/chef-bach/commit/f7b616a1f73361c2920d59af7fda1c4eaa9bb0a0) define a separate resource for graphite log cleanup. But that resource still [checks for `*.wsp` files instead of `*.log*` files](https://github.com/bloomberg/chef-bach/blob/f7b616a1f73361c2920d59af7fda1c4eaa9bb0a0/cookbooks/bcpc/recipes/graphite.rb#L191). This line needs to be corrected to actually have the logs cleaned up

**Comment by kiiranh** [comment]
It would also be could to keep logs only for the last `7` days instead of `15` to reduce used storage space, unless ofcourse they are compacted.

**Comment by pu239ppy** [comment]
I'll take it

**Comment by pu239ppy** [comment]
I am not going to change our defaults at this point, we can do this as a separate pull request

**Comment by kiiranh** [comment]
I believe this has been fixed.
