### ISSUE TITLE
Need to provide kerberos config for Phoenix

### ISSUE THREAD

**Issue by cbaenziger** [bloomberg/chef-bach#275]
Today, it looks like Phoenix hangs when running on a kerberized cluster. A blog post at http://bigdatanoob.blogspot.com/2013/09/connect-phoenix-to-secure-hbase-cluster.html looks to have what we need to do to configure it for kerberos.

**Comment by mlongob** [comment]
From reading http://docs.hortonworks.com/HDPDocuments/HDP2/HDP-2.3.0/bk_upgrading_hdp_manually/content/configure-phoenix-21.html I was able to get Phoenix to work on a Kerberized cluster just by setting an environment variable.

#### pssql.py
```
HBASE_CONF_PATH=/etc/hadoop/conf:/etc/hbase/conf /usr/hdp/current/phoenix-client/bin/psql.py f-bcpc-vm1.bcpc.example.com /usr/hdp/current/phoenix-client/doc/examples/STOCK_SYMBOL.sql /usr/hdp/current/phoenix-client/doc/examples/STOCK_SYMBOL.csv
```

#### sqlline.py
```
HBASE_CONF_PATH=/etc/hadoop/conf:/etc/hbase/conf /usr/hdp/current/phoenix-client/bin/sqlline.py f-bcpc-vm1.bcpc.example.com
```

**Comment by djh4230** [comment]
Could you please post me the configuration of phoenix which is in http://bigdatanoob.blogspot.com/2013/09/connect-phoenix-to-secure-hbase-cluster.html?
because there is nothing in this page now.
