### ISSUE TITLE
Add `OOZIE_URL` to motd or VIP

### ISSUE THREAD

**Issue by kiiranh** [bloomberg/chef-bach#279]
Tenants working on oozie want to know the `OOZIE_URL`. With multiple clusters, its hard to remember the URLs for all the clusters. We should add the [`OOZIE_URL`](https://github.com/kiiranh/chef-bach/blob/hdfsdu/cookbooks/bcpc-hadoop/recipes/hdfsdu_pre_fetch.rb#L14) to the [`motd`](https://github.com/bloomberg/chef-bach/blob/master/cookbooks/bach_common/templates/default/motd/bach-variables.erb#L27)

**Comment by cbaenziger** [comment]
I would much rather see us expose Oozie via the VIP, as Oozie should be HA and thus would have multiple URLs. Simply putting Oozie behind haproxy would work well as I understand it.
