### ISSUE TITLE
get_config issue about returning nothing result in silent fail

### ISSUE THREAD

**Issue by DrRayWang** [bloomberg/chef-bach#294]
Currently, `get_config()` return nil if password is not found in the data bag. In this case, it will fail password setting scenario like `get_config('password','mysql-graphite','os')` in [this](https://github.com/DrRayWang/chef-bach/blob/afff934491925cc970ed493b0f6a016764b270ba/cookbooks/bcpc/recipes/graphite.rb#L174-L179): 
```ruby
ruby_block "graphite-database-creation" do
    block do
        if not system "mysql -uroot -p#{get_config('mysql-root-password')} -e 'SELECT SCHEMA_NAME FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME = \"#{node['bcpc']['graphite_dbname']}\"'|grep \"#{node['bcpc']['graphite_dbname']}\"" then
            %x[ mysql -uroot -p#{get_config('mysql-root-password')} -e "CREATE DATABASE #{node['bcpc']['graphite_dbname']};"
                mysql -uroot -p#{get_config('mysql-root-password')} -e "GRANT ALL ON #{node['bcpc']['graphite_dbname']}.* TO '#{get_config('mysql-graphite-user')}'@'%' IDENTIFIED BY '#{get_config('password','mysql-graphite','os')}';"
                mysql -uroot -p#{get_config('mysql-root-password')} -e "GRANT ALL ON #{node['bcpc']['graphite_dbname']}.* TO '#{get_config('mysql-graphite-user')}'@'localhost' IDENTIFIED BY '#{get_config('password','mysql-graphite','os')}';"
```
We have another method `get_config!()` to raise error when `get_config()` return nil. Hence we should modify current `get_config!()` and use it for all the cases that get password from chef vault to shout out password missing case, like above code example.

**Comment by kiiranh** [comment]
The related PRs have been merged. This can be closed.
