### ISSUE TITLE
Dynamically configure bootstrap machine/host

### ISSUE THREAD

**Issue by amithkanand** [bloomberg/chef-bach#3]
In our current implementation, the bootstrap machine is created with values that are statically defined in `Vagrantfile` or bootstrap machine's box image itself. Some of these values are:
- Chef Environment Name
- IP Address for bootstrap machine
- Host name for bootstrap machine
Hard coding of these values makes it challenging when there is a requirement to build multiple bootstrap machines when working with multiple clusters.

One of the idea to automate this is to create a generic bootstrap box image file that will not have any configuration in it and then use `Vagrant` to provision the bootstrap machine with correct values that are defined in an environment file. The `Vagrantfile` should be able to do following:
- Parse an environment file that has information about the cluster to be built
- Create and configure network interface on the bootstrap host
- Upload correct environment to bootstrap host
- Create the correct environment within chef-server running on the bootstrap host
- Remove any stale boostrap vm from the chef-server running on bootstrap host
- Create and configure bootstrap node with correct values

**Comment by cbaenziger** [comment]
Amit, are you satisfied with the changes pushed in #22 ?

**Comment by amithkanand** [comment]
Yes. #22 took care of this issue.
