### ISSUE TITLE
Access to important logs on component failures

### ISSUE THREAD

**Issue by kiiranh** [bloomberg/chef-bach#304]
As observed on a cluster recently, if a region server goes down (looses Zookeeper connectivity or can't reach the namenode), region server spews its logs with exception messages. Depending on the setting for logs rolling, it is possible that all the allocated number of logs are filled with only exceptions. If one were to try and understand what went wrong with the region server, there is no way to find out without appropriate logs before and during the failure occured. 

There are a few things that can help in such scenarios:
- Copy-logs with quotas
  - Periodically copy important logs to HDFS or other backing store
- Alerts
  - Set alerts for a component going down, so one can quickly collect all debug information
- Trigger action
  - Failure alert can trigger an action which automatically collects debug information and stashes into  HDFS or other backing store
- Timeout
  - Components should have a timeout setting after which it will halt itself instead of continually trying to recover without success

**Comment by cbaenziger** [comment]
As to the quotas the concern is that copylogs could fill a cluster's HDFS when a component spews. Ideally we could use a recipe to run `hdfs dfsadmin setQuota` (or `setSpaceQuota`) to ensure we do not DoS HDFS. Perhaps Flume has some intelligence we could leverage too?
