### ISSUE TITLE
build_bins.sh rebuilds graphite related packages every time it runs

### ISSUE THREAD

**Issue by pu239ppy** [bloomberg/chef-bach#323]
It does not appear as -f detects file globs so [ -f python-pytz* ] or -f anything* will always fail.
There is no need to rebuild the cluster when testing this code, in fact the issue is that build_bins.sh will try to rebuild packages on subsequent runs.

**Comment by http-418** [comment]
I have been doing this with chef.

Unfortunately, I have not yet integrated the https_intracluster stuff.

https://github.com/http-418/chef-bach/blob/next/cookbooks/bach_repository/recipes/graphite.rb

**Comment by pu239ppy** [comment]
Pull request merged
