### ISSUE TITLE
Broken HTTPFS when Kerberos is enabled

### ISSUE THREAD

**Issue by mlongob** [bloomberg/chef-bach#328]
Some HTTPFS operations don't work with kerberos enabled.
Bug:

http://mydatanode:14000/webhdfs/v1/user/myuser/foo.txt?op=CREATE&overwrite=false
-> follow redirect to: http://mydatanode:14000/webhdfs/v1/user/myuser/foo.txt?op=CREATE&overwrite=false&data=true
This causes a Curl error with the following description:
Send failed since rewinding of the data stream failed

**Comment by bijugs** [comment]
``CREATE`` seems to work fine when HTTPFS is accessed through ``curl``.

**Comment by bijugs** [comment]
This is not an issue.
