### ISSUE TITLE
cluster-assign-roles.sh fails to Chef Vault os/ssh

### ISSUE THREAD

**Issue by cbaenziger** [bloomberg/chef-bach#345]
On an established cluster, for some reason I am hitting the following. This is when running `./cluster-assign-roles.sh CLUSTER hadoop`. Per the `cluster-assign-roles.sh` changes in Chef-BACH #212 and Chef-BACH #245 it was believed that nodes would have keys updated for their visibility as needed; it seems that is not happening?

For reference, the bootstrap node can see the vault item fine:

```
bootstrap:~/chef-bcpc$ sudo knife vault show os ssh -m client
id:          ssh
private-key: <key here>
```

While the node being Chef'd can not:

```
  * ruby_block[chef_vault_secret] action create
    - execute the ruby block chef_vault_secret

  * chef_vault_secret[ssh] action create_if_missing  
================================================================================
Error executing action `create_if_missing` on resource 'chef_vault_secret[ssh]'
================================================================================


ChefVault::Exceptions::SecretDecryption
---------------------------------------
os/ssh is not encrypted with your public key.  Contact an administrator of the vault item to encrypt for you!


Cookbook Trace:
---------------
/var/chef/cache/cookbooks/chef-vault/libraries/chef_vault_secret_provider.rb:67:in `load_current_resource'


Resource Declaration:
---------------------
# In /var/chef/cache/cookbooks/bcpc/recipes/certs.rb

 54: chef_vault_secret "ssh" do
 55:   data_bag 'os'
 56:   raw_data({ "private-key" => key.to_pem })
 57:   admins "#{ nodes },#{ bootstrap }"
 58:   search '*:*'
 59:   action :create_if_missing
 60: end
 61:



Compiled Resource:
------------------
# Declared in /var/chef/cache/cookbooks/bcpc/recipes/certs.rb:54:in `from_file'

chef_vault_secret("ssh") do
  action [:create_if_missing]
  retries 0
  retry_delay 2
  guard_interpreter :default
  cookbook_name "bcpc"
  recipe_name "certs"
  data_bag "os"
  raw_data {"private-key"=>"<new key here since node can not read old key>"}
  admins "cluster-r1n02.example.com,cluster-r1n03.example.com,cluster-r1n04.example.com,cluster-r1n05.example.com,cluster-r1n06.example.com,cluster-r1n07.example.com,cluster-r1n08.example.com,cluster-r1n10.example.com,cluster-r2n03.example.com,cluster-r2n04.example.com,cluster-r2n05.example.com,cluster-r2n06.example.com,cluster-r2n07.example.com,cluster-r2n08.example.com,cluster-r2n11.example.com,bcpc-cluster-bootstrap"
  search "*:*"
  id "ssh"
end


```

**Comment by cbaenziger** [comment]
Looking at `knife data bag show os ssh_keys|grep :|sed 's/:.*//'` I saw all machines and the bootstrap node present. To try and regenerate things I ran `knife vault rotate all keys` with no change. I then removed all nodes from the vault value with `for m in $(knife node list|grep -v bootstrap); do knife vault remove os ssh --admins $m --mode client; done` I then saw only the bootstrap node as an admin. I re-ran chef-client on the bootstrap to re-run the `certs.rb` recipe but was still ending up with issues so it seemed.

**Comment by http-418** [comment]
When I first logged in to examine nodes 3 and 4, their chef runs bombed on SSH, as expected.

Running `knife vault refresh os ssh` appears to have fixed the problem.   Chef runs complete without bombing on

Unfortunately I did not record the 'clients' list before running refresh.  It's possible that clients were missing from the chef solr index, so the search had a bad list pre-refresh.

**Comment by http-418** [comment]
Upon choosing a wider set of hosts to examine, not just 3 and 4, I found four failed to retrieve the os ssh secret when I kicked off a chef run.  All were present in the client list already.  I checked one of the four for matching public keys, and the public key was correct in the 'client' object.

I ran `knife vault refresh os ssh` again.   This time, it did not alter the behavior of the failing clients.

**Comment by http-418** [comment]
The failing nodes are definitely present in os/ssh_keys data_bag.   I am unable to manually decrypt the data on either a working node or a failing one, so the key is not in ascii inside the bag. 

It also doesn't match on a working and failing node, so whatever the binary dump is, it's not the shared key.

**Comment by http-418** [comment]
After another few refreshes and chef-client runs, I am now down to three failing nodes, but I have no idea why.

**Comment by http-418** [comment]
After manually decrypting the shared secret with a non-working client's key, I am successfully able to retrieve the encrypted data bag.   We do not have a data problem.  Something isn't working right in the chef client/server.

Next steps: debugger.

**Comment by http-418** [comment]
The problem was not as mysterious as it looked.  'os/ssh' was indeed working after a key rotation.  'os/*ssl*' was failing, and i didn't notice the one-letter change.

After a `sudo knife vault rotate all keys --mode client` on bootstrap, all nodes converge happily.

I still don't have a root cause, but I'll have to wait for another cluster to break before I can re-create the problem.
