### ISSUE TITLE
Updating JAVA_HOME property in config file doesn't restart services

### ISSUE THREAD

**Issue by kiiranh** [bloomberg/chef-bach#35]
There are two bugs:
1. I updated the node["bcpc"]["hadoop"]["java"] attribute to the oracle java home and rechefed the nodes (on VM cluster using cluster-assign-roles). The hadoop services (hbase master for eg) were not restarted. I killed the java processes on the nodes and then rechefed. Then the services were started with the updated JAVA_HOME property.

2. cookbooks/bcpc-hadoop/templates/default/hb_hbase-env.sh.erb explicitly exports JAVA_HOME instead of using the node["bcpc"]["hadoop"]["java"] attribute (line 108).

**Comment by cbaenziger** [comment]
Closing this particular issue as fixed in:
#111 and #139
