### ISSUE TITLE
Metric regions in transition

### ISSUE THREAD

**Issue by cbaenziger** [bloomberg/chef-bach#355]
Today our alarming system is based around JMX metrics. Some key HBase data we are missing is regions-in-transition. Either we should incorporate [HBASE-4348](https://issues.apache.org/jira/browse/HBASE-4348) metrics or find some way to report the results of `hbase hbck -summary`.

**Comment by leochen4891** [comment]
I have confirmed that the metrics for regions in transition (ritCount) is reported to JMX, since it is visible via JConsole. Next step is to add it to the jmxtrans configuration and do some test.

**Comment by leochen4891** [comment]
https://github.com/bloomberg/chef-bach/pull/498

**Comment by cbaenziger** [comment]
Still need to alarm on RITs...
