### ISSUE TITLE
mySQL stability

### ISSUE THREAD

**Issue by pu239ppy** [bloomberg/chef-bach#365]
-- Define a different temp directory for mysql's temp store as /tmp contains too many entries
-- should also set wsrep_notify_cmd to work with external alert script.  Need to integrate it with the node[:bcpc][:zabbix][:scripts][:mail] script. See https://www.percona.com/forums/questions-discussions/percona-xtradb-cluster/11039-handy-wsrep-notify-cmd-email-script for some inspiration -- this way even if MySQL dies we can get notified since Zabbix would be dead

**Comment by kiiranh** [comment]
Some more optimizations are recommended for Zabbix: https://www.zabbix.com/documentation/2.4/manual/appendix/performance_tuning
