### ISSUE TITLE
Disable unused diamond collectors

### ISSUE THREAD

**Issue by kiiranh** [bloomberg/chef-bach#370]
Currently, we have multiple [diamond collectors](https://github.com/bloomberg/chef-bach/blob/df10bcfe71fdd7943cfdcb8ec74d80c6570469ac/cookbooks/bcpc/templates/default/diamond.conf.erb#L166-L222) enabled. Since, not all of them are used, to reduce load on diamond, we should enable only those that are used and disable the others.

**Comment by pu239ppy** [comment]
Will be fixed by #405 closing #397 as it duplicates the work
