### ISSUE TITLE
Disk IO on root filesystem

### ISSUE THREAD

**Issue by pu239ppy** [bloomberg/chef-bach#374]
We have noticed that carbon-cache places a lot of load on the disk that it is writing to.  This adversely affects zookeeper which in turns affects Name Node and Resource Manager operation.  This also impacts mysql sst transfers and stability of the mysql cluster. Our BCPC-Hadoop head nodes which are currently hosting carbon caches allocate all available disks to hadoop operational storage such as dfs.namenode.name.dir, on head nodes we can reduce that count by one and dedicate a physical disk to carbon-cache and log carbon/graphite log storage

**Comment by kiiranh** [comment]
Can this issue be resolved?

**Comment by pu239ppy** [comment]
Not yet I prepared a few pull requests and opened an issue on carbon project for whiser file header caching grahite/whisper#347
