### ISSUE TITLE
Oozie HA and Job History Server incompatible

### ISSUE THREAD

**Issue by cbaenziger** [bloomberg/chef-bach#383]
Today on a machine running the role[BCPC-Hadoop-Head-MapReduce], the job history server requires the mapreduce principal a be fully qualified with hostname. However, if the current RM or JHS is running on a different machine, Oozie will also pickup this principal and fail with the following:

```
java.lang.IllegalArgumentException: Server has invalid Kerberos principal: 
mapred/cluster1-r1n02.example.com@REALM.EXAMPLE.COM]
org.apache.oozie.action.ActionExecutorException: JA009: 
java.lang.IllegalArgumentException: Server has invalid Kerberos principal: 
mapred/cluster1-r1n02.example.com@REALM.EXAMPLE.COM
```

To avoid this, we should specify the principal as mapred/_HOST or point to an Oozie specific `mapred-site.xml` as per [Oozie configuration](http://oozie.apache.org/docs/4.2.0/AG_HadoopConfiguration.html#Hadoop_Default_Configuration_Values) documentation.

**Comment by zsc1993916** [comment]
hi, i also encountered this problem recently, I'd be much appreciated if you could explain the solution in more detail, thanks
