### ISSUE TITLE
jmxtrans run_interval in bcpc-hadoop is overridden

### ISSUE THREAD

**Issue by leochen4891** [bloomberg/chef-bach#449]
The run_interval of jmxtrans is currently set in bcpc-hadoop/attributes/default.rb. Due to chef compile order, it is overridden and doesn't take effect. We may need to move it to somewhere else, such as bcpc-jmxtrans.

**Comment by pu239ppy** [comment]
We should probably move all jmx related attributes into bcpc_jmxtrans cookbook's attributes
