### ISSUE TITLE
Logic to enable YARN RM HA is incorrect

### ISSUE THREAD

**Issue by bijugs** [bloomberg/chef-bach#5]
The code in [yarn-site](https://github.com/bloomberg/chef-bach/blob/ef7dbd42f59c0e5bac69fe134de18c422d48067a/cookbooks/bcpc-hadoop/templates/default/hdp_yarn-site.xml.erb#L12) expects more than 2 nodes to run YARN RM which need to be changed to check for 2 RMs in the cluster.

**Comment by bijugs** [comment]
This is being fixed as part of HA enablement of various components in chef-bach move to HDP 2.2.

**Comment by cbaenziger** [comment]
Fixed in 5e236e96f26dabef8ac1118cd8fee3eb515d1112
