### ISSUE TITLE
[Branch Friendly] Can't build a new VM cluster using friendly branch code

### ISSUE THREAD

**Issue by bijugs** [bloomberg/chef-bach#507]
Tried to bring up a VM cluster using the code in branch ``friendly`` and it fails with the following issues. Looks like some un-tested code got merged into the ``friendly`` branch.

```
Recipe Compile Error in /var/chef/cache/cookbooks/bach_spark/attributes/default.rb
```
```
08:55:04  30>> default.bach_spark.environment.SPARK_LOCAL_IP = node.bcpc.floating.ip
```

**Comment by bijugs** [comment]
[This](https://github.com/bloomberg/chef-bach/commit/692c6b9e24e017995cd004cb966318ec91c60baf#diff-0c27760150486f45702becedb374a35eR30) change which got pulled into the {{friendly}} branch is causing the code to break.

**Comment by http-418** [comment]
'git blame' indicates that's from Amit's 'spark_enhance' changes.

reply@reply.github.com " data-digest="From: reply@reply.github.com " style="">

**Comment by bijugs** [comment]
Cluster build is successful using ``friendly`` branch after fixing the issue with the ``spark`` related components.
