### ISSUE TITLE
site.xml/env.sh generation error

### ISSUE THREAD

**Issue by bijugs** [bloomberg/chef-bach#580]
**Scenario 1:**
- Set ``node["bcpc"]["hadoop"]["hbase"]["bucketcache"]["enabled"]`` to ``true`` through ``chef`` environment.
- Set ``node["bcpc"]["hadoop"]["hbase"]["bucketcache"]["enabled"]`` to ``false`` through a wrapper cookbook which depends in ``bcpc-hadoop`` cookbook.

The logic in [hbase.rb attribute]( https://github.com/bloomberg/chef-bach/blob/master/cookbooks/bcpc-hadoop/attributes/hbase.rb#L103) sees the attribute value as ``true`` and adds the required properties to ``hbase-site.xml``.

While the logic in  [hbase_config.rb recipe]( https://github.com/bloomberg/chef-bach/blob/18913e592918a0025f45bd18a61dd187a935be2f/cookbooks/bcpc-hadoop/recipes/hbase_config.rb#L141) gets the value as ``false`` as expected due to which ``hbase`` regionserver fails to start. This needs to be looked into and similar situation may exists for other components.

**Comment by bijugs** [comment]
**Scenario 2:**

- No environment attribute node["bcpc"]["hadoop"]["hbase"]["bucketcache"]["enabled"] set in chef environment.
- Set node["bcpc"]["hadoop"]["hbase"]["bucketcache"]["enabled"] to ``true`` through a wrapper cookbook which depends in bcpc-hadoop cookbook.
The logic in [hbase.rb attribute](https://github.com/bloomberg/chef-bach/blob/master/cookbooks/bcpc-hadoop/attributes/hbase.rb#L103) sees the attribute value as ``false`` which is value set in ``bcpc-hadoop`` resulting in required properties not added to hbase-site.xml.

While the logic in [hbase_config.rb recipe](https://github.com/bloomberg/chef-bach/blob/18913e592918a0025f45bd18a61dd187a935be2f/cookbooks/bcpc-hadoop/recipes/hbase_config.rb#L141) sees the value ``true`` as expected.

In scenario 2, even though hbase starts fine, this is not the expected behavior when overriding attributes through a wrapper cookbook.

**Comment by cbaenziger** [comment]
@Biju, for scenario 1:
At which [precedent level](https://docs.chef.io/attributes.html#attribute-types) are the environment and wrapper cookbook setting the node attributes? Is the wrapper cookbook setting the attribute in its attribute file or a recipe?

**Comment by bijugs** [comment]
@cbaenziger , wrapper is setting the attributes at ``force_override`` level in its attribute. But the issue here looks like is due to compile time resolution in the ``chef-bach`` attribute file even before wrapper can override attributes.
