### ISSUE TITLE
Cannot derive 8bit node number

### ISSUE THREAD

**Issue by amithkanand** [bloomberg/chef-bach#588]
I am getting following error while chef-ing one of the head node. We need to figure out a correct process to handle this on an existing cluster.

```
============================================================================
Recipe Compile Error in /var/chef/cache/cookbooks/bcpc/recipes/keepalived.rb
============================================================================
RuntimeError
------------
Cannot derive 8bit node number for bcpc-vm1, the value 76 would overlap with existing node numbers: [218, 140, 39, 204, 76, 195, 211, 214, 207, 123]


Cookbook Trace:
---------------
  /var/chef/cache/cookbooks/bcpc/libraries/node_numbers.rb:35:in `bcpc_8bit_node_number'
  /var/chef/cache/cookbooks/bcpc/recipes/keepalived.rb:51:in `block in from_file'
  /var/chef/cache/cookbooks/bcpc/recipes/keepalived.rb:45:in `from_file'


Relevant File Content:
----------------------
/var/chef/cache/cookbooks/bcpc/libraries/node_numbers.rb:

 28:
 29:      other_8bit_node_numbers =
 30:        node.run_state['other_node_numbers'].map { |n| n.to_i % 255 }
 31:
 32:      if other_8bit_node_numbers.include?(my_8bit_value)
 33:        fail "Cannot derive 8bit node number for #{target_node[:hostname]}, " \
 34:          "the value #{my_8bit_value} would overlap with existing " \
 35>>         'node numbers: ' + other_8bit_node_numbers.inspect
 36:      end
 37:    end
 38:
 39:    my_8bit_value
 40:  end
 41:
```

**Comment by amithkanand** [comment]
Further investigation reveals that if a node number already exists it won't be replaced with a new node number using new logic. Look at code [here](./cookbooks/bcpc/attributes/default.rb). Currently the only clean way to replace a node number is the re-pxe the machine. The dirty way is to manually edit the node object and remove node number attribute.

**Comment by amithkanand** [comment]
Another issue I have found with new node number logic is that it changes node number on re-chef. The HDFS can go down If the node number is changed on a head node. I have experienced this twice while working on a cluster.

**Comment by http-418** [comment]
The old node number is supposed to be used if present.  That is the intended behavior.   The new logic should only be used if setting up a new cluster that has never had node numbers assigned.
