### ISSUE TITLE
Add oozie-client to worker role/node

### ISSUE THREAD

**Issue by amithkanand** [bloomberg/chef-bach#60]
Currently, `oozie-client` is only installed on the node that is running `oozie-server` process causing worker/gateway nodes to not have `oozie-client`.  With this approach users are not able to access oozie server from any of the worker/gateway node and are bounded to log on to the node running `oozie-server` process. 
To fix this we need add `oozie-client` installation to worker/gateway nodes.

**Comment by cbaenziger** [comment]
Similarly, `bcpc-hadoop::hive` is not in [BCPC-Hadoop-Worker](https://github.com/bloomberg/chef-bach/blob/94689b93d2abf6bf05c370b09555c85c46559560/roles/BCPC-Hadoop-Worker.json) either.

**Comment by amithkanand** [comment]
Worker nodes currently install `hive` using [`bcpc-hadoop::datanode`](https://github.com/bloomberg/chef-bach/blob/master/cookbooks/bcpc-hadoop/recipes/datanode.rb#L62) recipe. We need to fix this as part of re-factoring project.

**Comment by kiiranh** [comment]
Fixed under PR#83. Can be closed.

**Comment by bijugs** [comment]
Some of the changes mentioned here for Hive and Yarn are implemented as part of PR #112 . Please see the [commit list](https://github.com/bloomberg/chef-bach/pull/112/commits). Closing this issue since the original issue is fixed as part of PR #83.
