### ISSUE TITLE
bcpc-hadoop::yarnproxy recipe is not used anywhere

### ISSUE THREAD

**Issue by bijugs** [bloomberg/chef-bach#64]
bcpc-hadoop::yarnproxy is not used in any of the roles and hence yarn-proxyserver and yarn-historyserver are not installed in the cluster.

**Comment by cbaenziger** [comment]
We have the history server installed as part of [`role[BCPC-Hadoop-Head-MapReduce]`](https://github.com/bloomberg/chef-bach/blob/5fc1c4290c960512909467f3f8df400aeaf19bba/roles/BCPC-Hadoop-Head-MapReduce.json#L10).

But indeed [`bcpc-hadoop::yarnproxy`](https://github.com/bloomberg/chef-bach/blob/fae16780f88045c61a74ce555d539167465b31b2/cookbooks/bcpc-hadoop/recipes/yarnproxy.rb) is still orphaned -- and installing the history server redundantly now.
