### ISSUE TITLE
Incorrect port set for Yarn app attempt log

### ISSUE THREAD

**Issue by amithkanand** [bloomberg/chef-bach#652]
After  `BACH-341` the functionality for viewing `Yarn` app attempts log is broken due to incorrect port set for [`yarn.log.server.url`](https://github.com/bloomberg/chef-bach/blob/master/cookbooks/bcpc-hadoop/recipes/yarn_site.rb#L225). The correct port is `19888`.

**Comment by cbaenziger** [comment]
Looks like this can be closed...
