### ISSUE TITLE
Provide a way to overwrite GC options through hbase-env.sh

### ISSUE THREAD

**Issue by amithkanand** [bloomberg/chef-bach#654]
The current code base creates a [local variable](https://github.com/bloomberg/chef-bach/blob/master/cookbooks/bcpc-hadoop/recipes/hbase_config.rb#L164) to generate configurations for `hbase-env`. This prevents overwriting or adding any additional values through environment or wrapper cookbook.  We need a chef attribute instead of local variable to be able to provide custom values through wrapper/environment.

**Comment by http-418** [comment]
Whoops, this issue was fixed long ago in PR #659 and we kept adding it to milestones.
