### ISSUE TITLE
Zookeeper log4j issues

### ISSUE THREAD

**Issue by cbaenziger** [bloomberg/chef-bach#658]
When one runs `zookeeper-client`, they will see the following spurious error:

```
ubuntu@bcpc-vm1:~$ zookeeper-client -server f-`hostname`:2181 
log4j:ERROR setFile(null,true) call failed.
java.io.FileNotFoundException: /var/log/zookeeper/zookeeper-ubuntu-cli-bcpc-vm1.log (Permission denied)
        at java.io.FileOutputStream.open0(Native Method)
```

Further, we fail to use such a descriptive log location for the zookeeper daemon which logs to: `/var/log/zookeeper/zookeeper.log` and `/var/log/zookeeper/zookeeper.out`

We should not produce a spurious error when starting a client binary and should record logs into a file which provides both the daemon and hostname of the process.

**Comment by aespinosa** [comment]
Should be solved by #1233 as well
