### ISSUE TITLE
Chef-BACH #659 grows the node object without bound

### ISSUE THREAD

**Issue by cbaenziger** [bloomberg/chef-bach#667]
The following lines use `node.set` from Chef-BACH #659 and will therefore grow the node object of a machine without bound:
hbase_config.rb lines [164](https://github.com/amithkanand/chef-bach/blob/b093407ed6f495dfb8aa3cbb351d59869ab1baec/cookbooks/bcpc-hadoop/recipes/hbase_config.rb#L164), [167](https://github.com/amithkanand/chef-bach/blob/b093407ed6f495dfb8aa3cbb351d59869ab1baec/cookbooks/bcpc-hadoop/recipes/hbase_config.rb#L167), [170](https://github.com/amithkanand/chef-bach/blob/b093407ed6f495dfb8aa3cbb351d59869ab1baec/cookbooks/bcpc-hadoop/recipes/hbase_config.rb#L170), [179](https://github.com/amithkanand/chef-bach/blob/b093407ed6f495dfb8aa3cbb351d59869ab1baec/cookbooks/bcpc-hadoop/recipes/hbase_config.rb#L179), [184](https://github.com/amithkanand/chef-bach/blob/b093407ed6f495dfb8aa3cbb351d59869ab1baec/cookbooks/bcpc-hadoop/recipes/hbase_config.rb#L184).

Further, for any machine which successfully converged with this code will damage its node object and need to have the following data removed:
* `['bcpc']['hadoop']['hbase']['env']['HBASE_OPTS']`
* `['bcpc']['hadoop']['hbase']['env']['HBASE_MASTER_OPTS']`
* `['bcpc']['hadoop']['hbase']['env']['HBASE_REGIONSERVER_OPTS']`

**Comment by http-418** [comment]
pull 676 corrects this once and for all
