### ISSUE TITLE
Access denied for user graphite to database graphite on Graphite's web ui

### ISSUE THREAD

**Issue by leochen4891** [bloomberg/chef-bach#678]
After an VM cluster is built from uefi_support, the Graphite's web ui shows a green error message.
"OperationalError: (1044, "Access denied for user 'graphite'@'%' to database 'graphite'")"
![graphite_web_error](https://cloud.githubusercontent.com/assets/3683228/18752030/1a94bee8-80af-11e6-894d-07bf3fcec690.PNG)

**Comment by http-418** [comment]
I was able to re-create this issue.  The cause is that we attempt to use the database name `graphite.*` in a `mysql_database` resource, when we should just be using `graphite`.  It's fixed.
