### ISSUE TITLE
bootstrap-gpg-key is filling up /tmp!

### ISSUE THREAD

**Issue by cbaenziger** [bloomberg/chef-bach#739]
It looks like an issue as clusters run longterm is that [`cluster_local_repository.rb`](https://github.com/bloomberg/chef-bach/blob/1083b974c3d90a540fd80f4891dbfdb44ffeb3e7/cookbooks/bcpc/recipes/cluster_local_repository.rb#L57) will fill up `/tmp/` bring machines to their knees:
````
ubuntu@cluster-machine-r1n04:~$ ls -l /tmp/bootstrap-gpg-key* | wc -l
6418
````

We do not even need to do tempfile gyrations if we simply use the GPGME gem's [`fingerprint`](http://www.rubydoc.info/github/ueno/ruby-gpgme/GPGME%2FKey%3Afingerprint) method.

**Comment by http-418** [comment]
This is fixed by deleting the tempfile in PR #755 

(I like the GPGME gem solution better, though)
