### ISSUE TITLE
encoding issue when running auto-install test vms script on Mac OS

### ISSUE THREAD

**Issue by RayAtBloomberg** [bloomberg/chef-bach#74]
This is one line in automated_install.sh got error when running on MAC OS: 
```
[[ -n "$PROXY" ]] && $SEDINPLACE "s#\(\"bootstrap\": {\)#\1\n\"proxy\" : \"http://$PROXY\",\n#" environments/${ENVIRONMENT}.json
```
it executed and translated to: "bootstrap:n"proxy" : "http://proxy....",n in the Test-Laptop Json file. This results in error.
Because MAC OS takes BSD's Sed version that is different from Unix's Sed.

**Comment by cbaenziger** [comment]
Fixed in #84
