### ISSUE TITLE
Test cases for HA

### ISSUE THREAD

**Issue by amithkanand** [bloomberg/chef-bach#776]
- [x] During initial cluster build the cluster is built with two NameNodes running in HA mode
- [x] After the cluster is build, a third head node `JournalNode`, `Zookeeper` is added successfully.
- [x] After addition of third head node existing cluster is converged successfully and  new head node is added to configuration files on existing head nodes
- [x] A `JournalNode` head node can be destroyed and restored successfully
- [x] A `NameNode` head node can be destroyed and restored successfully
- [x] Both the NameNode can switch roles  i.e. primary can be re-installed as standby and standby can be reinstalled as primary

**Comment by http-418** [comment]
Journalnodes can be added/formatted successfully after merging PR #803

**Comment by http-418** [comment]
My failures on our test cluster were driven by an invalid jn_txn_fmt file stored in a data bag.

Pre-existing JN data was fine, but any new JN failed to contribute to the quorum.  Once enough JNs were re-PXE'd, I lost the ability to fail over.

By erasing the jn_txn_fmt data bag item and re-chefing the namenode masnter, I was able to correct the problem.  Now failover works correctly.
