### ISSUE TITLE
Build broken without a no_proxy

### ISSUE THREAD

**Issue by cbaenziger** [bloomberg/chef-bach#787]
Currently, if one runs with out a `$no_proxy` set, one may hit:
````
  * execute[new-pip-upgrade-packaging] action run

    ================================================================================
    Error executing action `run` on resource 'execute[new-pip-upgrade-packaging]'
    ================================================================================

    Errno::ENOENT
    -------------
    No such file or directory - /usr/local/bin/pip

    Resource Declaration:
    ---------------------
    # In /var/chef/cache/cookbooks/bach_repository/recipes/python.rb

     86:   execute "new-pip-upgrade-#{package_name}" do
     87:     command '/usr/local/bin/pip ' \
     88:       "install #{package_name} --no-use-wheel --upgrade " \
     89:       "#{pip_cert_option} #{pip_cheese_shop_option}"
     90:     environment pip_environment
     91:     not_if {
     92:       get_version =
     93:         Mixlib::ShellOut.new("/usr/local/bin/pip show #{package_name} | " \
     94:                              "grep ^Version | awk '{print $2}'")
     95:       min_version = Gem::Version.new(min_version)
     96:       actual_version = Gem::Version.new(get_version.run_command.stdout.chomp)
     97:       actual_version >= min_version
     98:     }
     99:   end
    100: end
````

**Comment by cbaenziger** [comment]
For me, it seems [this commit](https://github.com/bloomberg/chef-bach/pull/786/commits/1a26f419faf79eff42a1c503897a1a1910050c1e) fixes the issue.

**Comment by cbaenziger** [comment]
I also hit, the following line from `automated_install.sh`:
`+ vagrant ssh -c 'cd chef-bcpc; PATH=/opt/chefdk/embedded/bin:/usr/bin:/bin bundle install --path vendor/bundle'`

This eventually failed with a series of lines akin to: `Gem::RemoteFetcher::FetchError: Errno::ETIMEDOUT: Connection timed out - connect(2) for "rubygems.org" port 443 (https://rubygems.org/gems/public_suffix-2.0.5.gem)`

Next, if this line has a proxy, I hit an issue with [`wait-for-hosts.sh`](https://github.com/bloomberg/chef-bach/commit/7d1633654563df8fecd4f0b0ca3a738a48586eb8#diff-4bf39b80894db1640f9eb2b9e987e6abR12)

I overcame this with the following [commit](https://github.com/bloomberg/chef-bach/pull/786/commits/72c4d1c2dfc08745560841b7b8cf96e669c8bb25).

**Comment by cbaenziger** [comment]
Another issue folks have been seeing is the install failing on bcpc-vm1 with:
Time to call off the cluster chase but I died with:
```  * bash[format namenode] action run

    ================================================================================
    Error executing action `run` on resource 'bash[format namenode]'
    ================================================================================

    Mixlib::ShellOut::ShellCommandFailed
    ------------------------------------
    Expected process to exit with [0], but received '1'
    ---- Begin output of "bash"  "/tmp/chef-script20170222-7332-q7qaek" ----
    STDOUT: Formatting using clusterid: CID-2c25797f-055b-4270-8c49-9b6ab1606d57
    STDERR: Java HotSpot(TM) 64-Bit Server VM warning: ignoring option PermSize=128m; support was removed in 8.0
    Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=256m; support was removed in 8.0
```

I have tried to fix this with [this commit](https://github.com/bloomberg/chef-bach/pull/786/commits/9812b2cba8214edcbb04a4fd88d9101a756fe13d) thanks to @leochen4891

**Comment by vt0r** [comment]
Fixed in #790

**Comment by cbaenziger** [comment]
PR #786 to fix these issues is still progressing

**Comment by http-418** [comment]
I haven't recreated the problem with `bundle install`, which is why I cherry-picked the pip fix in #790.  That problem was easy to re-create and verify.

**Comment by vt0r** [comment]
PR #786 just got merged anyway, so closing again :)

**Comment by cbaenziger** [comment]
For more info, I see that my `no_proxy` is getting set to `127.0.0.1,<IPs for my DNS servers(?)>,10.0.100.2,172.16.100.2,192.168.100.2,clay-desktop,clay-desktop,.0.100.,10.0.100.*,,localhost` (Notice the double `,,`.) This seems to be messing up the `gem source -a https://rubygems.org` command as it does not use a proxy for the connection to `https://rubygems.org`; unsetting my `$no_proxy` made it use the proxy though.
