### ISSUE TITLE
HDFS checks run by workers need to be keyed per host

### ISSUE THREAD

**Issue by cbaenziger** [bloomberg/chef-bach#793]
Today, running on a suitably large cluster I keep having Chef run failures due to races between testing existence of a file to verify HDFS is okay and trying to clean it up. E.g.:
```
  * bash[tez-remove-check-file] action run
================================================================================
Error executing action `run` on resource 'bash[tez-remove-check-file]'
================================================================================


Mixlib::ShellOut::ShellCommandFailed
------------------------------------
Expected process to exit with [0], but received '1'
---- Begin output of "bash"  "/tmp/chef-script20170224-56656-17zmquj" ----
STDOUT: 
STDERR: rm: `/user/hdfs/chef-tez-test': No such file or directory
---- End output of "bash"  "/tmp/chef-script20170224-56656-17zmquj" ----
Ran "bash"  "/tmp/chef-script20170224-56656-17zmquj" returned 1
```

This is part of [tez.rb](https://github.com/bloomberg/chef-bach/blob/0ace6521edc678be43c06e2821c73a00bf0dcc28/cookbooks/bcpc-hadoop/recipes/tez.rb#L44-L50) and runs on all worker nodes. But since the file name is the same, there is a race between the file being tested for existence and -- another node -- first deleting the file, that machine being at the same point in its Chef run.

**Comment by vt0r** [comment]
Fixed in #797
