### ISSUE TITLE
Graphite recipes attempt to write to the graphite_disk directory before clearing old whisper files

### ISSUE THREAD

**Issue by http-418** [bloomberg/chef-bach#814]
If the graphite_disk directory is located on a full filesystem, it is no longer possible to re-PXE the node.  The graphite recipes attempt to write data to the graphite_disk directory *before* running the `find` to clear old data.  This will fail on a full filesystem.

**Comment by cbaenziger** [comment]
@http-418 is it not possible to re-PXE or re-Chef the node?
