### ISSUE TITLE
Generic bootstrap does not regenerate UFW rules to allow TFTP access

### ISSUE THREAD

**Issue by cbaenziger** [bloomberg/chef-bach#82]
If one setups a VM bootstrap image and then uses `Vagrant.baremetal` to re-provision the UFW rules are not initially updated. The rules from `ufw.rb` do not update on the re-provision but seem to update subsequently. Disabling the `ufw` service and re-chefing the bootstrap seems to add the new IP in for the TFTP rule (though the old IP is left in as well).

If one sees TFTP boot failing, simply check `iptables -L` under the `ufw-user-input` chain for TFTP and ensure the IP address listed is for the correct machine.

**Comment by amithkanand** [comment]
This is fixed in PR #143
