### ISSUE TITLE
Need to handle GRA*.log files

### ISSUE THREAD

**Issue by cbaenziger** [bloomberg/chef-bach#870]
Today we dump out 10's of thousands of `/var/lib/mysql/GRA_*.log` files we should either not produce these or do something intelligent with them.

For more on them, see:
* [What About GRA_- log files](https://www.percona.com/blog/2012/12/19/percona-xtradb-cluster-pxc-what-about-gra_-log-files/)
* [Galera Cluster Logs](http://galeracluster.com/documentation-webpages/log.html)

**Comment by pu239ppy** [comment]
Per the first link listed, I suspect these logs have a very short shelf life, why don't we just clean them out if they get older then some agreed age?  This age should probably not exceed a day or two.
