### ISSUE TITLE
Secure RM HTTP access

### ISSUE THREAD

**Issue by amithkanand** [bloomberg/chef-bach#885]
BACH clusters use default value for `hadoop.http.authentication.type` which allows submission of the job using "simple" authentication mechanism, i.e. by providing only the user.name.

We need to secure this by setting `hadoop.http.authentication.type` to use `kerberos`.

**Comment by pu239ppy** [comment]
Will this affect users' ability to browse the YARN Web UI?

**Comment by amithkanand** [comment]
Yes, it will. Users will have to configure their browser for authentication to access secure service.

**Comment by ronny-macmaster** [comment]
This is a good link: https://hadoop.apache.org/docs/r2.7.3/hadoop-project-dist/hadoop-common/core-default.xml

Try setting both ```hadoop.http.authentication.type``` and  ```hadoop.security.authentication``` to ```kerberos```

**Comment by amithkanand** [comment]
Since we build kerberized clusters, `hadoop.security.authentication` is already set to `kerberos`

**Comment by amithkanand** [comment]
This is fixed in PR #888
