### ISSUE TITLE
Axioms of Chef-BACH Architecture

### ISSUE THREAD

**Issue by cbaenziger** [bloomberg/chef-bach#89]
We should have an architecture plan for our sprawling codebase. This would help us understand where components should go and what future development should look like.
### Today

We have code in the following cookbooks today:
- [bcpc](https://github.com/bloomberg/chef-bach/tree/28e504e928a2cf3e964bd61237963540c23cfe73/cookbooks/bcpc) -  Cluster Core OS
- [bcpc-hadoop](https://github.com/bloomberg/chef-bach/tree/28e504e928a2cf3e964bd61237963540c23cfe73/cookbooks/bcpc-hadoop)  - Cluster Hadoop Centric Ecosystem Components
- [kafka-bcpc](https://github.com/bloomberg/chef-bach/tree/28e504e928a2cf3e964bd61237963540c23cfe73/cookbooks/kafka-bcpc) - Kafka Centric Wrappers
- [bcpc_jmxtrans](https://github.com/bloomberg/chef-bach/tree/28e504e928a2cf3e964bd61237963540c23cfe73/cookbooks/bcpc_jmxtrans) - JMXTrans Wrappers
- to be upstream Chef community cookbooks - [cobblerd](https://github.com/cbaenziger/cobbler-cookbook), [hannibal](https://github.com/bloomberg/chef-bach/tree/28e504e928a2cf3e964bd61237963540c23cfe73/cookbooks/hannibal), etc.
### Proposal for the future

One direction we can move to looks like:
- `bcpc` -> `bach_os`
  - Remove all OpenStack components
- `bcpc-hadoop` -> `hadoop`
  - Eventaully this would be wrapper cookbooks around a core of community Hadoop ecosystem component cookbooks
  - Move [`graphite_to_zabbix`](https://github.com/bloomberg/chef-bach/blob/28e504e928a2cf3e964bd61237963540c23cfe73/cookbooks/bcpc-hadoop/recipes/graphite_to_zabbix.rb) to `bach_os` as it is not Hadoop related
- `kafka-bcpc` -> `bach_kafka` (or `kafka_wrapper`?)
- `bcpc_jmxtrans` -> `bach_jmxtrans` (or `jmxtrans_wrapper`?)
#### Creation of `bach_bootstrap`

In the above envisioned architecture, the `bach_bootstrap` cookbook is envisioned. It would consist of the following code today:
- `bcpc::bootstrap*`
- `bcpc-hadoop::{java,maven}_config` wrappers
- [`build_bins.sh`](https://github.com/bloomberg/chef-bach/blob/28e504e928a2cf3e964bd61237963540c23cfe73/build_bins.sh) would move to a recipe(s)
### General axioms guiding Chef-BACH
- Code should be runnable on a periodic basis (e.g. every five minutes) without ill effect
- Ideally code can be upgraded in place; upgrade which can not happen in place should be achievable via a reinstall of the machine to get an identical system with the new features
  - For a cluster node this is achieved via HA, data replication, etc. and a PXE re-install
  - For a bootstrap node how do we achieve this?
### Axioms guiding `bach_bootstrap`:
- Recipes can be run Internet connected once
  - All necessary binaries from the Internet would be stored in what is today `chef-bcpc/bins`
- Recipes run with a pre-stashed artifact in `chef-bcpc/bins` should nolonger try to talk to Internet
### Axioms guiding `bach_os`:
- Machines do not talk to Internet
- `bach_os` may setup an OS for Hadoop, Kafka or unaffiliated types of systems (e.g. Solr machines)
### Axioms guiding `hadoop`:
- Systems serving an HTTP interface running on a "head" node should be active-active
- Services deployed on the cluster should be built elsewhere and only the service deployed in hadoop (e.g. `hannibal_build.rb` run on bootstrap versus `hannibal_deploy.rb` run on the Hadoop cluster)
## Fuzzy Areas:
- Though not strictly following [Role Cookbooks and Wrapper Cookbooks](http://realityforge.org/code/2012/11/19/role-cookbooks-and-wrapper-cookbooks.html) patterns, it is good to not rely on roles or overload the environment too an unnecessary degree -- but where to draw the line?
- If a wrapper cookbook is just setting attributes, can they be reasonably set as attributes on the bcpc-hadoop cookbook? (Or should they explicitly be wrapper cookbooks?)
- Where do we put generic cluster operations library code (e.g. [`get_nodes_for`](https://github.com/bloomberg/chef-bach/blob/28e504e928a2cf3e964bd61237963540c23cfe73/cookbooks/bcpc/libraries/utils.rb#L128-L135) or [`wait_until_ready`](https://github.com/bloomberg/chef-bach/blob/28e504e928a2cf3e964bd61237963540c23cfe73/cookbooks/hannibal/libraries/hannibal_helper.rb#L6-L22))
  - Do we make this all go in a `bach_cluster_ops` cookbook
  - Or, do we bundle this code as a gem?

**Comment by amithkanand** [comment]
As discussed with team, I would recommend breaking each component into its own individual cookbook. For example:
### HDFS
Cookbooks for `HDFS` should be called `bach_hdfs` and is responsible for setting up HDFS related components:
* Name Node (Primary, Standby and Secondary)
* Data Node
* Journal Node
* ZKFS

In addition, the attributes should also follow the cookbook's name as their namespace. In case of `HDFS` all `HDFS` related attributes should start with `default[:bach][:hdfs]` and should further be divided into individual configuration section of `HDFS`. For example:
* `OS` related => `default[:bach][:hdfs][:os]`
* `Name Node` related => `default[:bach][:hdfs][:namenode]`
* `Data Node` related => `default[:bach][:hdfs][:datanode]` and so on.
