### ISSUE TITLE
Datanode and others throw "OutOfMemoryException: java.lang.OutOfMemoryError"

### ISSUE THREAD

**Issue by cbaenziger** [bloomberg/chef-bach#895]
We have seen datanodes (and then many other processes) have issues with `malloc` on our machines -- while still having plenty of memory on the system. Interestingly, the kernel OOM killer does not run and even root is unable to spawn processes. Usually the precipitating event is seeing `OutOfMemoryException: java.lang.OutOfMemoryError: unable to create new native thread` in our datanode logs.

In investigation, we have found the datanode (and often JMXTrans) are locked in creating threads until they have nearly 64k threads each. We have found `vm.max_map_count` is by default 128k on Ubuntu 14.04 and each thread uses a kernel map. This appears to DoS the entire box for users and the affected processes causing byzantine failure of threads. (For example, the datanode becomes a zombie running but no longer heartbeating to the namenode.)

**Comment by cbaenziger** [comment]
A couple of fixes proposed are:
* Use `jvmkill` agent as mentioned in #470 [comment](https://github.com/bloomberg/chef-bach/issues/470#issuecomment-299044878)
* Set the `vm.max_map_count` higher. Canonical recommended the heuristic `grep MemTotal /proc/meminfo | awk '{printf "%.0f",$2}')/16 | bc`
* We can also add memory map monitoring to Graphite per process via Diamond

**Comment by vt0r** [comment]
Merging #901 (done earlier today) should at least help with this issue. The `jvmkill` solution is also being investigated in parallel. Leaving this issue open to track the implementation of suggestions 1/3.
