### ISSUE TITLE
oozie url exported as part of the user profile

### ISSUE THREAD

**Issue by ekund** [bloomberg/chef-bach#905]
It would be great if the user profile exported the cluster's oozie url so you did not need to type it in on every command or export it yourself, as there is only 1 oozie url per cluster.

The profile would have something like this in it:
`export OOZIE_URL=<oozie_url>`

**Comment by http-418** [comment]
This is included in PR #896, and it will very likely be a part of the chef-bach "3.0" release

https://github.com/bloomberg/chef-bach/pull/896/commits/1de547107f8eb2f427e5e4dc89cd7f530d6420f5

**Comment by http-418** [comment]
#896 is merged, so, this should be appearing on dev clusters pretty soon.
