### ISSUE TITLE
Chef test vms in parallel in automated_install.sh

### ISSUE THREAD

**Issue by kiiranh** [bloomberg/chef-bach#92]
Currently, in tests/automated_install.sh lines 79-82, there is a for loop which chefs (cluster-assign-roles) each Hadoop vm serially. This does not setup the services on the vms correctly. 
Replace the for loop with a single cluster-assign-roles statement without specifying a VM.
This is supposed to set /etc/hosts correctly on all the nodes without having to chef them in a particular order.

**Comment by cbaenziger** [comment]
Fixed in #94
