### ISSUE TITLE
Configure heap size for Hive processes

### ISSUE THREAD

**Issue by amithkanand** [bloomberg/chef-bach#96]
Currently, hive processes `hive-metastore` and `hive-server2` are started with default heap size of 1GB which is sufficient for most of the workloads. In cases where queries/data sets are larger to process the heap size must be reconfigured to a larger value. In absence of right heap size one would see errors akin to:
````
(ProcessFunction.java:process(41)) - Internal error processing ExecuteStatement
java.lang.OutOfMemoryError: Java heap space
````

The heap size can be changed by setting `HADOOP_HEAPSIZE` under `hive-env.sh` to a larger value.

**Comment by bijugs** [comment]
Fixed as part of PR #97
