### ISSUE TITLE
Cobbler 2.6 is no longer hosted on opensuse and is EOL move to 2.8

### ISSUE THREAD

**Issue by pu239ppy** [bloomberg/chef-bach#964]
This URL http://download.opensuse.org/repositories/home:/libertas-ict:/cobbler26/xUbuntu_14.04/ is now invalid, we should consider 2.8.

**Comment by cbaenziger** [comment]
I am seeing if we can use a branch of the cobbler-cookbook I built for testing EFI; it builds Cobbler from source (my[source_build branch](https://github.com/cbaenziger/cobbler-cookbook/tree/source_build)).

**Comment by pu239ppy** [comment]
Clay is already working on this

**Comment by http-418** [comment]
The 2.8 mirrors host dummy packages with no contents.

We need to get in touch with @jmaas to figure out what to do next

**Comment by cbaenziger** [comment]
I have the Cobbler bits installing using my [source_build](https://github.com/bloomberg/cobbler-cookbook/pull/6) branch and it installs a working Cobbler to my bootstrap on the [multi-cluster](https://github.com/bloomberg/chef-bach/pull/788) branch.

**Comment by jmaas** [comment]
Hi,

We have serious constraints on development, somewhere in time the debian packaging for opensuse build service was broken. I do not have the skills/time to fix it. I'm struggling with bugs/releases as it is. 

If you guys have some bits to contribute that would be awesome!

**Comment by cbaenziger** [comment]
Closing as we can successfully use source builds of Cobbler for now and do not have the expertise to get the OpenSuSE builds going again.
