### ISSUE TITLE
Setting ownership to yarn before yarn exists

### ISSUE THREAD

**Issue by pu239ppy** [bloomberg/chef-bach#966]
[Line 74 hadoop_config](https://github.com/bloomberg/chef-bach/blob/master/cookbooks/bcpc-hadoop/recipes/hadoop_config.rb#L74) ensures that yarn.exclude is rendered from an environment vriable #951 introduced this feature, however, it sets the ownership to `yarn`, and this user has not been created at the time.  The original code just sets mode 

```ruby
hadoop_non_templates.each do |t|
  template "/etc/hadoop/conf/#{t}" do
    source "hdp_#{t}.erb"
    mode 0644
  end
end
```  

This might be easier then trying to figure out at which point the yarn user needs to be added

**Comment by http-418** [comment]
On clusters with external auth, the directory is always configured before any hadoop recipes run.

We can just add a recipe that checks for the necessary user and creates it if missing, then include it before anything that might need it.  Multiple inclusions is safe in Chef

**Comment by pu239ppy** [comment]
Setting the user is not necessary as the file permissions 644 ensure that whoever needs to read it can do so.  It is sufficient reverting back to that removes the necessity to add more code and checks
