### ISSUE TITLE
setup-oozie.sh prepare-war fails with HDP 2.6.1.17-1

### ISSUE THREAD

**Issue by pu239ppy** [bloomberg/chef-bach#970]
cp: omitting directory ‘/usr/hdp/current/oozie-client/libext/mysql-connector-java.jar’
Failed: copying jar /usr/hdp/current/oozie-client/libext/mysql-connector-java.jar to staging

This happens because /usr/hdp/current/oozie-client/libext/mysql-connector-java.jar is a symlink to /usr/share/java/mysql-connector-java.jar which happens to be a directory, this obviously breaks cp

For now fixing recipe
````
diff --git a/cookbooks/bcpc-hadoop/recipes/oozie.rb b/cookbooks/bcpc-hadoop/recipes/oozie.rb
index b32e0f25..35fb4b0d 100644
--- a/cookbooks/bcpc-hadoop/recipes/oozie.rb
+++ b/cookbooks/bcpc-hadoop/recipes/oozie.rb
@@ -96,7 +96,7 @@ end

 [
   '/usr/share/HDP-oozie/ext-2.2.zip',
-  '/usr/share/java/mysql-connector-java.jar',
+  '/usr/share/java/mysql-connector-java.jar/mysql-connector-java.jar',
   "/usr/hdp/#{hdp_rel}/hadoop/lib/hadoop-lzo-0.6.0.#{hdp_rel}.jar"
 ].each do |dst|
   link "#{OOZIE_LIB_PATH}/libext/#{File.basename(dst)}" do
````

**Comment by aespinosa** [comment]
mysql-connector-java.jar as a directory was introduced in #960
