### ISSUE TITLE
Add logic to disable HBase region replication

### ISSUE THREAD

**Issue by bijugs** [bloomberg/chef-bach#990]
When HBase region replication is enabled it creates a peer  ``region_replica_replication``. Need to add logic to the code to disable this peer if region replication is disabled.

```
disable_peer 'region_replica_replication'

```

**Comment by leochen4891** [comment]
Got this error

Got this error when building a VM cluster.

Recipe: bcpc-hadoop::hbase_repl
  * bash[stop_repl_remove_repl_peer] action run (skipped due to only_if)
  * bash[disable_hbase_region_repl_peer] action run
    [execute] /tmp/chef-script20171016-25575-1656kfr: line 1: hbase: command not found
    
    ================================================================================
    Error executing action `run` on resource 'bash[disable_hbase_region_repl_peer]'
    ================================================================================
    
    Mixlib::ShellOut::ShellCommandFailed
    ------------------------------------
    Expected process to exit with [0], but received '127'
    ---- Begin output of "bash"  "/tmp/chef-script20171016-25575-1656kfr" ----
    STDOUT: 
    STDERR: /tmp/chef-script20171016-25575-1656kfr: line 1: hbase: command not found
    ---- End output of "bash"  "/tmp/chef-script20171016-25575-1656kfr" ----
    Ran "bash"  "/tmp/chef-script20171016-25575-1656kfr" returned 127
    
    Resource Declaration:
    ---------------------
    # In /var/chef/cache/cookbooks/bcpc-hadoop/recipes/hbase_repl.rb
    
     35:   bash "disable_hbase_region_repl_peer" do
     36:     code <<-EOH
     37:       echo "disable_peer 'region_replica_replication'"|hbase shell
     38:       EOH
     39:     not_if "echo list_peers|hbase shell|grep region_replica_replication|grep ENABLED"
     40:     user 'hbase'
     41:   end
     42: end
    
    Compiled Resource:
    ------------------
    # Declared in /var/chef/cache/cookbooks/bcpc-hadoop/recipes/hbase_repl.rb:35:in `from_file'
    
    bash("disable_hbase_region_repl_peer") do
      action [:run]
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      command "disable_hbase_region_repl_peer"
      backup 5
      returns 0
      user "hbase"
      code "      echo \"disable_peer 'region_replica_replication'\"|hbase shell\n"
      interpreter "bash"
      declared_type :bash
      cookbook_name "bcpc-hadoop"
      recipe_name "hbase_repl"
      not_if "echo list_peers|hbase shell|grep region_replica_replication|grep ENABLED"
    end
    
    Platform:
    ---------
    x86_64-linux

**Comment by bijugs** [comment]
@leochen4891 , FYI. the change was tested on an existing cluster and not on a fresh cluster. Looks like this is breaking on a fresh VM cluster. Correct?

**Comment by cbaenziger** [comment]
Yes, I see this breaking a build of master @bijugs

**Comment by cbaenziger** [comment]
But more because `bcpc-hadoop::hbase_repl` is called before we install `hbase` in [role::BCPC-Hadoop-Head-HBase](https://github.com/bloomberg/chef-bach/blob/25e17a96cacaa4ecf5d46002f2f5374c14add9be/stub-environment/roles/BCPC-Hadoop-Head-HBase.json#L6-L7)?

**Comment by bijugs** [comment]
Yes. Looks like we had a role[BCPC-Hadoop-Head] in the role file for head node and it got removed which made the repl recipe the first one. Refer [this](https://github.com/bijugs/chef-bach/blob/ad6e79381262d14399242234a89c6c7210fb2829/roles/BCPC-Hadoop-Head-HBase.json).

**Comment by cbaenziger** [comment]
The original issue and some rework have been performed. I am closing this unless we see related issues crop up again.
